/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BOM = 1,
  sym_string_line = 2,
  sym_start_symbol = 3,
  sym_open_brace = 4,
  sym_close_brace = 5,
  sym_open_paren = 6,
  sym_close_paren = 7,
  sym_open_comment = 8,
  sym_close_comment = 9,
  sym_text = 10,
  sym_inner_text = 11,
  sym_if_ = 12,
  sym_else_if_ = 13,
  sym_else_ = 14,
  sym_while_ = 15,
  sym_for_ = 16,
  sym_match_ = 17,
  sym_extends_ = 18,
  aux_sym_extends_directive_token1 = 19,
  aux_sym_comment_block_token1 = 20,
  sym_source_file = 21,
  sym__template = 22,
  sym__inner_template = 23,
  sym_extends_directive = 24,
  sym__block = 25,
  sym_comment_block = 26,
  sym_rust_stmt = 27,
  sym_rust_stmt_head = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_rust_stmt_repeat1 = 30,
  aux_sym_rust_stmt_repeat2 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BOM] = "\ufeff",
  [sym_string_line] = "string_line",
  [sym_start_symbol] = "start_symbol",
  [sym_open_brace] = "open_brace",
  [sym_close_brace] = "close_brace",
  [sym_open_paren] = "open_paren",
  [sym_close_paren] = "close_paren",
  [sym_open_comment] = "open_comment",
  [sym_close_comment] = "close_comment",
  [sym_text] = "text",
  [sym_inner_text] = "inner_text",
  [sym_if_] = "if_",
  [sym_else_if_] = "else_if_",
  [sym_else_] = "else_",
  [sym_while_] = "while_",
  [sym_for_] = "for_",
  [sym_match_] = "match_",
  [sym_extends_] = "extends_",
  [aux_sym_extends_directive_token1] = "extends_directive_token1",
  [aux_sym_comment_block_token1] = "comment_block_token1",
  [sym_source_file] = "source_file",
  [sym__template] = "_template",
  [sym__inner_template] = "_inner_template",
  [sym_extends_directive] = "extends_directive",
  [sym__block] = "_block",
  [sym_comment_block] = "comment_block",
  [sym_rust_stmt] = "rust_stmt",
  [sym_rust_stmt_head] = "source_file",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rust_stmt_repeat1] = "rust_stmt_repeat1",
  [aux_sym_rust_stmt_repeat2] = "rust_stmt_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BOM] = anon_sym_BOM,
  [sym_string_line] = sym_string_line,
  [sym_start_symbol] = sym_start_symbol,
  [sym_open_brace] = sym_open_brace,
  [sym_close_brace] = sym_close_brace,
  [sym_open_paren] = sym_open_paren,
  [sym_close_paren] = sym_close_paren,
  [sym_open_comment] = sym_open_comment,
  [sym_close_comment] = sym_close_comment,
  [sym_text] = sym_text,
  [sym_inner_text] = sym_inner_text,
  [sym_if_] = sym_if_,
  [sym_else_if_] = sym_else_if_,
  [sym_else_] = sym_else_,
  [sym_while_] = sym_while_,
  [sym_for_] = sym_for_,
  [sym_match_] = sym_match_,
  [sym_extends_] = sym_extends_,
  [aux_sym_extends_directive_token1] = aux_sym_extends_directive_token1,
  [aux_sym_comment_block_token1] = aux_sym_comment_block_token1,
  [sym_source_file] = sym_source_file,
  [sym__template] = sym__template,
  [sym__inner_template] = sym__inner_template,
  [sym_extends_directive] = sym_extends_directive,
  [sym__block] = sym__block,
  [sym_comment_block] = sym_comment_block,
  [sym_rust_stmt] = sym_rust_stmt,
  [sym_rust_stmt_head] = sym_source_file,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rust_stmt_repeat1] = aux_sym_rust_stmt_repeat1,
  [aux_sym_rust_stmt_repeat2] = aux_sym_rust_stmt_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BOM] = {
    .visible = true,
    .named = false,
  },
  [sym_string_line] = {
    .visible = true,
    .named = true,
  },
  [sym_start_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_open_brace] = {
    .visible = true,
    .named = true,
  },
  [sym_close_brace] = {
    .visible = true,
    .named = true,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_open_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_close_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_inner_text] = {
    .visible = true,
    .named = true,
  },
  [sym_if_] = {
    .visible = true,
    .named = true,
  },
  [sym_else_if_] = {
    .visible = true,
    .named = true,
  },
  [sym_else_] = {
    .visible = true,
    .named = true,
  },
  [sym_while_] = {
    .visible = true,
    .named = true,
  },
  [sym_for_] = {
    .visible = true,
    .named = true,
  },
  [sym_match_] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_extends_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__template] = {
    .visible = false,
    .named = true,
  },
  [sym__inner_template] = {
    .visible = false,
    .named = true,
  },
  [sym_extends_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_rust_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_rust_stmt_head] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rust_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rust_stmt_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_head = 2,
  field_path = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_head] = "head",
  [field_path] = "path",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 4},
  [3] = {.index = 6, .length = 1},
  [4] = {.index = 7, .length = 1},
  [5] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 0, .inherited = true},
    {field_head, 0, .inherited = true},
  [2] =
    {field_body, 0, .inherited = true},
    {field_body, 1, .inherited = true},
    {field_head, 0, .inherited = true},
    {field_head, 1, .inherited = true},
  [6] =
    {field_head, 0},
  [7] =
    {field_path, 3},
  [8] =
    {field_body, 2},
    {field_head, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 16,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 28,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 40,
  [41] = 37,
  [42] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '"', 1,
        '\'', 2,
        '(', 45,
        ')', 46,
        '*', 5,
        '@', 40,
        'e', 22,
        'f', 25,
        'i', 16,
        'm', 10,
        'w', 18,
        '{', 43,
        '}', 44,
        0xfeff, 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(31);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(103);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(105);
      END_STATE();
    case 5:
      if (lookahead == '@') ADVANCE(48);
      END_STATE();
    case 6:
      if (lookahead == '@') ADVANCE(68);
      END_STATE();
    case 7:
      if (lookahead == '@') ADVANCE(93);
      END_STATE();
    case 8:
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(81);
      if (lookahead == 'f') ADVANCE(83);
      if (lookahead == 'i') ADVANCE(75);
      if (lookahead == 'm') ADVANCE(71);
      if (lookahead == 'w') ADVANCE(77);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 9:
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(94);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(95);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(101);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(100);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 31:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 32:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 33:
      if (eof) ADVANCE(36);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(52);
      if (lookahead == 'w') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 34:
      if (eof) ADVANCE(36);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == 0xfeff) ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '@') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BOM);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BOM);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string_line);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_start_symbol);
      if (lookahead == '*') ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_start_symbol);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '@') ADVANCE(68);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_start_symbol);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '@') ADVANCE(93);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_open_brace);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_close_brace);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_close_paren);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_open_comment);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_close_comment);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(52);
      if (lookahead == 'w') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == 0xfeff) ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'e') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'e') ADVANCE(97);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'f') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'h') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'h') ADVANCE(60);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(62);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'l') ADVANCE(65);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(64);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 's') ADVANCE(55);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == '{') ADVANCE(68);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(81);
      if (lookahead == 'f') ADVANCE(83);
      if (lookahead == 'i') ADVANCE(75);
      if (lookahead == 'm') ADVANCE(71);
      if (lookahead == 'w') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'a') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'c') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'f') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'f') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'h') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'h') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 'r') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 's') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == 't') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(94);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(101);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(99);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(95);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_inner_text);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_if_);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_else_if_);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_else_);
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_else_);
      if (lookahead == ' ') ADVANCE(59);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_else_);
      if (lookahead == ' ') ADVANCE(80);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_while_);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_for_);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_match_);
      if (lookahead != 0 &&
          lookahead != '@' &&
          lookahead != '{') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_extends_);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_extends_directive_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_comment_block_token1);
      if (lookahead == '*') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_comment_block_token1);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_comment_block_token1);
      if (lookahead == '*') ADVANCE(106);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 33},
  [3] = {.lex_state = 33},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 33},
  [9] = {.lex_state = 33},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 35},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 35},
  [15] = {.lex_state = 35},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 35},
  [18] = {.lex_state = 35},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 35},
  [23] = {.lex_state = 35},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 35},
  [26] = {.lex_state = 35},
  [27] = {.lex_state = 35},
  [28] = {.lex_state = 35},
  [29] = {.lex_state = 35},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 104},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 104},
  [42] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BOM] = ACTIONS(1),
    [sym_string_line] = ACTIONS(1),
    [sym_start_symbol] = ACTIONS(1),
    [sym_open_brace] = ACTIONS(1),
    [sym_close_brace] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_close_paren] = ACTIONS(1),
    [sym_open_comment] = ACTIONS(1),
    [sym_close_comment] = ACTIONS(1),
    [sym_if_] = ACTIONS(1),
    [sym_else_if_] = ACTIONS(1),
    [sym_else_] = ACTIONS(1),
    [sym_while_] = ACTIONS(1),
    [sym_for_] = ACTIONS(1),
    [sym_match_] = ACTIONS(1),
    [sym_extends_] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym__template] = STATE(14),
    [sym_extends_directive] = STATE(23),
    [sym__block] = STATE(14),
    [sym_comment_block] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BOM] = ACTIONS(5),
    [sym_start_symbol] = ACTIONS(7),
    [sym_open_comment] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(36), 1,
      sym_rust_stmt_head,
    ACTIONS(15), 3,
      sym_start_symbol,
      sym_open_comment,
      sym_text,
    ACTIONS(17), 6,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [23] = 5,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(36), 1,
      sym_rust_stmt_head,
    ACTIONS(21), 3,
      sym_start_symbol,
      sym_open_comment,
      sym_text,
    ACTIONS(23), 6,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [46] = 4,
    STATE(5), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(42), 1,
      sym_rust_stmt_head,
    ACTIONS(15), 4,
      sym_start_symbol,
      sym_close_brace,
      sym_open_comment,
      sym_inner_text,
    ACTIONS(17), 6,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [67] = 4,
    STATE(5), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(42), 1,
      sym_rust_stmt_head,
    ACTIONS(21), 4,
      sym_start_symbol,
      sym_close_brace,
      sym_open_comment,
      sym_inner_text,
    ACTIONS(23), 6,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [88] = 1,
    ACTIONS(26), 10,
      sym_start_symbol,
      sym_close_brace,
      sym_open_comment,
      sym_inner_text,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [101] = 6,
    ACTIONS(17), 1,
      sym_else_,
    ACTIONS(30), 1,
      sym_extends_,
    STATE(2), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(25), 1,
      sym_rust_stmt,
    STATE(36), 1,
      sym_rust_stmt_head,
    ACTIONS(28), 5,
      sym_if_,
      sym_else_if_,
      sym_while_,
      sym_for_,
      sym_match_,
  [124] = 2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 9,
      sym_start_symbol,
      sym_open_comment,
      sym_text,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [139] = 2,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 9,
      sym_start_symbol,
      sym_open_comment,
      sym_text,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [154] = 1,
    ACTIONS(36), 10,
      sym_start_symbol,
      sym_close_brace,
      sym_open_comment,
      sym_inner_text,
      sym_if_,
      sym_else_if_,
      sym_else_,
      sym_while_,
      sym_for_,
      sym_match_,
  [167] = 5,
    ACTIONS(17), 1,
      sym_else_,
    STATE(4), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(31), 1,
      sym_rust_stmt,
    STATE(42), 1,
      sym_rust_stmt_head,
    ACTIONS(28), 5,
      sym_if_,
      sym_else_if_,
      sym_while_,
      sym_for_,
      sym_match_,
  [187] = 6,
    ACTIONS(7), 1,
      sym_start_symbol,
    ACTIONS(9), 1,
      sym_open_comment,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym_text,
    STATE(15), 1,
      sym_extends_directive,
    STATE(22), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [209] = 5,
    ACTIONS(17), 1,
      sym_else_,
    STATE(2), 1,
      aux_sym_rust_stmt_repeat2,
    STATE(25), 1,
      sym_rust_stmt,
    STATE(36), 1,
      sym_rust_stmt_head,
    ACTIONS(28), 5,
      sym_if_,
      sym_else_if_,
      sym_while_,
      sym_for_,
      sym_match_,
  [229] = 5,
    ACTIONS(9), 1,
      sym_open_comment,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      sym_start_symbol,
    ACTIONS(44), 1,
      sym_text,
    STATE(17), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [248] = 5,
    ACTIONS(9), 1,
      sym_open_comment,
    ACTIONS(42), 1,
      sym_start_symbol,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym_text,
    STATE(18), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [267] = 5,
    ACTIONS(50), 1,
      sym_start_symbol,
    ACTIONS(52), 1,
      sym_close_brace,
    ACTIONS(54), 1,
      sym_open_comment,
    ACTIONS(56), 1,
      sym_inner_text,
    STATE(19), 4,
      sym__inner_template,
      sym__block,
      sym_comment_block,
      aux_sym_rust_stmt_repeat1,
  [286] = 5,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      sym_start_symbol,
    ACTIONS(63), 1,
      sym_open_comment,
    ACTIONS(66), 1,
      sym_text,
    STATE(17), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [305] = 5,
    ACTIONS(9), 1,
      sym_open_comment,
    ACTIONS(42), 1,
      sym_start_symbol,
    ACTIONS(44), 1,
      sym_text,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(17), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [324] = 5,
    ACTIONS(50), 1,
      sym_start_symbol,
    ACTIONS(54), 1,
      sym_open_comment,
    ACTIONS(71), 1,
      sym_close_brace,
    ACTIONS(73), 1,
      sym_inner_text,
    STATE(21), 4,
      sym__inner_template,
      sym__block,
      sym_comment_block,
      aux_sym_rust_stmt_repeat1,
  [343] = 5,
    ACTIONS(50), 1,
      sym_start_symbol,
    ACTIONS(54), 1,
      sym_open_comment,
    ACTIONS(73), 1,
      sym_inner_text,
    ACTIONS(75), 1,
      sym_close_brace,
    STATE(21), 4,
      sym__inner_template,
      sym__block,
      sym_comment_block,
      aux_sym_rust_stmt_repeat1,
  [362] = 5,
    ACTIONS(77), 1,
      sym_start_symbol,
    ACTIONS(80), 1,
      sym_close_brace,
    ACTIONS(82), 1,
      sym_open_comment,
    ACTIONS(85), 1,
      sym_inner_text,
    STATE(21), 4,
      sym__inner_template,
      sym__block,
      sym_comment_block,
      aux_sym_rust_stmt_repeat1,
  [381] = 5,
    ACTIONS(9), 1,
      sym_open_comment,
    ACTIONS(42), 1,
      sym_start_symbol,
    ACTIONS(44), 1,
      sym_text,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(17), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [400] = 5,
    ACTIONS(9), 1,
      sym_open_comment,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym_text,
    ACTIONS(42), 1,
      sym_start_symbol,
    STATE(22), 4,
      sym__template,
      sym__block,
      sym_comment_block,
      aux_sym_source_file_repeat1,
  [419] = 5,
    ACTIONS(50), 1,
      sym_start_symbol,
    ACTIONS(54), 1,
      sym_open_comment,
    ACTIONS(88), 1,
      sym_close_brace,
    ACTIONS(90), 1,
      sym_inner_text,
    STATE(20), 4,
      sym__inner_template,
      sym__block,
      sym_comment_block,
      aux_sym_rust_stmt_repeat1,
  [438] = 2,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(94), 2,
      sym_start_symbol,
      sym_open_comment,
  [447] = 2,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(98), 2,
      sym_start_symbol,
      sym_open_comment,
  [456] = 2,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(102), 2,
      sym_start_symbol,
      sym_open_comment,
  [465] = 2,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(106), 2,
      sym_start_symbol,
      sym_open_comment,
  [474] = 2,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(110), 2,
      sym_start_symbol,
      sym_open_comment,
  [483] = 2,
    ACTIONS(104), 1,
      sym_inner_text,
    ACTIONS(106), 3,
      sym_start_symbol,
      sym_close_brace,
      sym_open_comment,
  [492] = 2,
    ACTIONS(92), 1,
      sym_inner_text,
    ACTIONS(94), 3,
      sym_start_symbol,
      sym_close_brace,
      sym_open_comment,
  [501] = 2,
    ACTIONS(112), 1,
      sym_string_line,
    ACTIONS(114), 1,
      sym_close_paren,
  [508] = 2,
    ACTIONS(116), 1,
      sym_open_paren,
    ACTIONS(118), 1,
      aux_sym_extends_directive_token1,
  [515] = 1,
    ACTIONS(120), 1,
      sym_close_paren,
  [519] = 1,
    ACTIONS(122), 1,
      sym_open_brace,
  [523] = 1,
    ACTIONS(124), 1,
      sym_open_brace,
  [527] = 1,
    ACTIONS(126), 1,
      aux_sym_comment_block_token1,
  [531] = 1,
    ACTIONS(128), 1,
      sym_close_comment,
  [535] = 1,
    ACTIONS(130), 1,
      sym_close_comment,
  [539] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [543] = 1,
    ACTIONS(134), 1,
      aux_sym_comment_block_token1,
  [547] = 1,
    ACTIONS(136), 1,
      sym_open_brace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 67,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 101,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 139,
  [SMALL_STATE(10)] = 154,
  [SMALL_STATE(11)] = 167,
  [SMALL_STATE(12)] = 187,
  [SMALL_STATE(13)] = 209,
  [SMALL_STATE(14)] = 229,
  [SMALL_STATE(15)] = 248,
  [SMALL_STATE(16)] = 267,
  [SMALL_STATE(17)] = 286,
  [SMALL_STATE(18)] = 305,
  [SMALL_STATE(19)] = 324,
  [SMALL_STATE(20)] = 343,
  [SMALL_STATE(21)] = 362,
  [SMALL_STATE(22)] = 381,
  [SMALL_STATE(23)] = 400,
  [SMALL_STATE(24)] = 419,
  [SMALL_STATE(25)] = 438,
  [SMALL_STATE(26)] = 447,
  [SMALL_STATE(27)] = 456,
  [SMALL_STATE(28)] = 465,
  [SMALL_STATE(29)] = 474,
  [SMALL_STATE(30)] = 483,
  [SMALL_STATE(31)] = 492,
  [SMALL_STATE(32)] = 501,
  [SMALL_STATE(33)] = 508,
  [SMALL_STATE(34)] = 515,
  [SMALL_STATE(35)] = 519,
  [SMALL_STATE(36)] = 523,
  [SMALL_STATE(37)] = 527,
  [SMALL_STATE(38)] = 531,
  [SMALL_STATE(39)] = 535,
  [SMALL_STATE(40)] = 539,
  [SMALL_STATE(41)] = 543,
  [SMALL_STATE(42)] = 547,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rust_stmt, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rust_stmt, 1, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rust_stmt_repeat2, 2, 0, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat2, 2, 0, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat2, 2, 0, 2), SHIFT_REPEAT(35),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat2, 3, 0, 3),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rust_stmt_repeat2, 3, 0, 3),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rust_stmt_repeat2, 4, 0, 5),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat2, 4, 0, 5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rust_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rust_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_directive, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_directive, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_directive, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_directive, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_block, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_block, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_directive, 5, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_directive, 5, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rust_stmt_head, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rshtml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rshtml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
